doc(comparison.md): OTEL now has windows support
SumoLogic/sumologic-otel-collector pull request #1025
Opened 2023-02-28 16:33 UTC by rnishtala-sumo

https://github.com/SumoLogic/sumologic-otel-collector/blob/otel-windows-support-doc/docs/comparison.md

2023-02-28 21:40 UTC, amdprophet requested changes
Just a few small things, looks good otherwise.

2023-02-28 21:40 UTC, amdprophet commented on docs/comparison.md
> +  <li>Windows OS
Just "Windows" here (remove the "OS").

2023-02-28 21:40 UTC, amdprophet commented on docs/comparison.md
> +For more information, please refer to the [windows event log receiver](https://github.com/rnishtala-sumo/opentelemetry-collector-contrib/edit/main/receiver/windowseventlogreceiver/README.md) readme.
URL should be https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/windowseventlogreceiver/README.md.

2023-02-28 21:40 UTC, amdprophet commented on docs/comparison.md
> +For more information, please refer to the [windows performance counter receiver](https://github.com/rnishtala-sumo/opentelemetry-collector-contrib/edit/main/receiver/windowsperfcountersreceiver/READM
URL should be https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/windowsperfcountersreceiver/README.md.

2023-03-01 06:49 UTC, amdprophet approved these changes

2023-03-01 07:04 UTC, sumo-drosiek commented on docs/comparison.md
> +*Note: The following sources are not supported by the OpenTelemetry collector yet:
```suggestion
*Note:* The following sources are not supported by the OpenTelemetry collector yet:
```

What does it actually mean? For me it sounds like we do not support it but listing here, which doesn't make much sense

2023-03-01 07:07 UTC, sumo-drosiek reviewed
Please use Reference-style link with meaningful names: https://www.markdownguide.org/basic-syntax/#reference-style-links

e.g.
```
[windows performance counter receiver][windowsperfcountersreceiver]
```

```
[windowsperfcountersreceiver]: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/windowsperfcountersreceiver/README.md
```

2023-03-01 13:29 UTC, sumo-drosiek commented on docs/comparison.md
> +*Note: The following sources are not supported by the OpenTelemetry collector yet:
I think we should put them it in the table and it will be better

2023-03-01 13:34 UTC, sumo-drosiek commented on docs/comparison.md
> +*Note: The following sources are not supported by the OpenTelemetry collector yet:
It makes sense when I re-read it, but it would be nice to add it to the comparison table as well :)

2023-03-01 13:38 UTC, sumo-drosiek commented on docs/comparison.md
> +<li>Windows Collection
I believe we should split it for specific sources, as we started to support part of them

2023-03-01 14:15 UTC, sumo-drosiek commented on docs/comparison.md
> +<li>[Remote Windows Event Log Source](https://help.sumologic.com/docs/send-data/installed-collectors/sources/remote-windows-event-log-source)
I think we have omit links as they are issues with rendering

2023-03-01 14:15 UTC, sumo-drosiek commented on docs/comparison.md
> +#### Windows Log Event Receiver
We should add it to supported sources table

2023-03-01 14:53 UTC, merged