docs: change `logLevel` to `loglevel` for Logging exporter
SumoLogic/sumologic-otel-collector pull request #1037
Opened 2023-03-02 09:12 UTC by astencel-sumo

`logLevel` only worked due to a bug in the upstream that was "fixed" in v0.71.0, breaking many configurations.

2023-03-02 09:20 UTC, sumo-drosiek requested changes
Shouldn't it be `verbosity: detailed`?

![image](https://user-images.githubusercontent.com/58699848/222386041-003f2e3c-5782-4ea3-9ac2-9537fba46747.png)

https://github.com/open-telemetry/opentelemetry-collector/tree/v0.72.0/exporter/loggingexporter#getting-started

2023-03-02 10:01 UTC, astencel-sumo commented
> Shouldn't it be `verbosity: detailed`?
> 
> ![image](https://user-images.githubusercontent.com/58699848/222386041-003f2e3c-5782-4ea3-9ac2-9537fba46747.png)
> 
> https://github.com/open-telemetry/opentelemetry-collector/tree/v0.72.0/exporter/loggingexporter#getting-started

I wanted to do this separately, but I can change it right into `verbosity`.

2023-03-02 10:06 UTC, sumo-drosiek approved these changes

2023-03-03 10:44 UTC, swiatekm-sumo approved these changes

2023-03-06 10:01 UTC, merged